/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kbcgame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DEEPAK
 */
public class AddQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestion
     */
    public AddQuestion() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Question");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 40, 60, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(136, 33, 510, 29);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(135, 80, 170, 40);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(476, 80, 170, 40);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 140, 170, 40);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(480, 150, 170, 40);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(140, 200, 240, 40);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(154, 260, 150, 40);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(503, 260, 143, 40);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(154, 313, 150, 40);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(503, 313, 143, 40);

        jButton1.setText("Insert Question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 420, 120, 50);

        jButton2.setText("Edit Questions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 420, 130, 50);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Option A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 50, 14);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Option B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 80, 60, 14);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Option C");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 60, 14);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Option D");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 150, 60, 20);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Correct Answer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 210, 90, 14);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Audience Poll 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 280, 90, 14);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Audience Poll 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 270, 100, 14);

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Audience Poll 3");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 330, 90, 14);

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Audience Poll 4");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 330, 90, 14);

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 440, 80, 40);

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\hee.jpg")); // NOI18N
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 770, 560);

        setSize(new java.awt.Dimension(737, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        EditQuestions eq=new EditQuestions();
        eq.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String question=jTextField1.getText();
        String oa=jTextField2.getText();
        String ob=jTextField3.getText();
        String oc=jTextField4.getText();
        String od=jTextField5.getText();
        String ca=jTextField6.getText();
        String ap1=jTextField7.getText();
        String ap2=jTextField8.getText();
        String ap3=jTextField9.getText();
        String ap4=jTextField10.getText();
        
        int status=0;
        
        if(question.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the question");
        }
        else if(oa.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the option A");
        }
        else if(ob.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the option B");
        }
        else if(oc.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the option C");
        }
        else if(od.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the option D");
        }
        else if(ca.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the correct option");
        }
        else if(ap1.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the audience poll 1");
        }
        else if(ap2.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the audience poll 2");
        }
        else if(ap3.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the audience poll 3");
        }
        else if(ap4.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter the audience poll 4");
        }
        else
        {
            try
            {
                Connection con=DbConnectivity.connect();
                PreparedStatement ps=con.prepareStatement("insert into KBC_QUESTION values(?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, question);
                ps.setString(2, oa);
                ps.setString(3, ob);
                ps.setString(4, oc);
                ps.setString(5, od);
                ps.setString(6, ap1);
                ps.setString(7, ap2);
                ps.setString(8, ap3);
                ps.setString(9, ap4);
                ps.setString(10, ca);
                ps.setInt(11, status);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Question inserted successfully");

                AddQuestion aq=new AddQuestion();
                aq.setVisible(true);
                setVisible(false);
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        AdminPanel ap=new AdminPanel();
        ap.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
