/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KBCAudiencepoll.java
 *
 * Created on Mar 10, 2013, 9:18:45 PM
 */
package kbcgame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.Timer;
import javax.swing.text.html.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DEEPAK
 */
public class KBCAudiencepoll extends javax.swing.JFrame
{
    
    String qqq;
    String ques1;
    Integer ii1;
    Integer ii2;
    Integer ii3;
    Integer ii4;
    Timer time1;
    String correctanswer;
    
    final static int duration1=50;   //means we dont want to change the value
    int i1;
    Timer timer1 = new Timer( duration1, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //throw new UnsupportedOperationException("Not supported yet.");
            if(i1==ii1)
            {
                timer1.stop();
            }
            i1=i1+1;
            jProgressBar1.setValue(i1);
        }
    });
    
    
    final static int duration2=50;   //means we dont want to change the value
    int i2;
    Timer timer2 = new Timer( duration2, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //throw new UnsupportedOperationException("Not supported yet.");
            if(i2==ii2)
            {
                timer2.stop();
            }
            i2=i2+1;
            jProgressBar2.setValue(i2);
        }
    });
    
    
    final static int duration3=50;   //means we dont want to change the value
    int i3;
    Timer timer3 = new Timer( duration3, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //throw new UnsupportedOperationException("Not supported yet.");
            if(i3==ii3)
            {
                timer3.stop();
            }
            i3=i3+1;
            jProgressBar3.setValue(i3);
        }
    });
    
    
    final static int duration4=50;   //means we dont want to change the value
    int i4;
    Timer timer4 = new Timer( duration4, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //throw new UnsupportedOperationException("Not supported yet.");
            if(i4==ii4)
            {
                timer4.stop();
            }
            i4=i4+1;
            jProgressBar4.setValue(i4);
        }
    });
    
    
    final static int duration5=50;   //means we dont want to change the value
    int iii;
    Timer timer5 = new Timer( duration5, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //throw new UnsupportedOperationException("Not supported yet.");
            if(iii==130)
            {
                timer5.stop();
                JOptionPane.showMessageDialog(rootPane, "'"+correctanswer+"' gets the highest votes");
                setVisible(false);
                
                time1.start();
            }
            iii=iii+1;
        }
    });
    
    
    /** Creates new form KBCAudiencepoll */
    public KBCAudiencepoll(String qqq, Timer time) {
        initComponents();
        ques1=qqq;
        time1=time;
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(740, 34, 0, 0);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Option-1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 120, 260, 50);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Option-2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 200, 260, 50);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Option-3", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 280, 260, 50);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 51));
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Option-4", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 360, 260, 50);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 153));
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Question", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 30, 620, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/audiencepoll.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 450, 90, 60);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(380, 130, 260, 30);

        jProgressBar2.setStringPainted(true);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(380, 210, 260, 30);

        jProgressBar3.setStringPainted(true);
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(380, 290, 260, 30);

        jProgressBar4.setStringPainted(true);
        getContentPane().add(jProgressBar4);
        jProgressBar4.setBounds(380, 380, 260, 30);

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\hepp.jpg")); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)), "AUDIENCE POLL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 730, 520);

        setSize(new java.awt.Dimension(746, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
    try
    {
        jButton1.setEnabled(false);
        
        Connection con=DbConnectivity.connect();
        PreparedStatement ps=con.prepareStatement("select * from KBC_QUESTION where QUESTION='"+ques1+"'");
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
            String str1=rs.getString("AUDIENCE_POLL_1");
            ii1=Integer.parseInt(str1);
            String str2=rs.getString("AUDIENCE_POLL_2");
            ii2=Integer.parseInt(str2);
            String str3=rs.getString("AUDIENCE_POLL_3");
            ii3=Integer.parseInt(str3);
            String str4=rs.getString("AUDIENCE_POLL_4");
            ii4=Integer.parseInt(str4);
            String question=rs.getString("QUESTION");
            jLabel11.setText(question);
            String opt1=rs.getString("OPTION_A");
            jLabel7.setText(opt1);
            String opt2=rs.getString("OPTION_B");
            jLabel8.setText(opt2);
            String opt3=rs.getString("OPTION_C");
            jLabel9.setText(opt3);
            String opt4=rs.getString("OPTION_D");
            jLabel10.setText(opt4);
            correctanswer=rs.getString("CORRECT_ANSWER");
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
    timer1.start();
    timer2.start();
    timer3.start();
    timer4.start();
    timer5.start();
    
}//GEN-LAST:event_jButton1ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    
    jLabel11.setText(ques1);
    try
    {
        Connection con=DbConnectivity.connect();
        PreparedStatement ps=con.prepareStatement("select * from KBC_QUESTION where QUESTION='"+ques1+"'");
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
            jLabel7.setText(rs.getString("OPTION_A"));
            jLabel8.setText(rs.getString("OPTION_B"));
            jLabel9.setText(rs.getString("OPTION_C"));
            jLabel10.setText(rs.getString("OPTION_D"));
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KBCAudiencepoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KBCAudiencepoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KBCAudiencepoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KBCAudiencepoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KBCAudiencepoll(null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    // End of variables declaration//GEN-END:variables
}
