/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KBCCallafriend.java
 *
 * Created on Mar 10, 2013, 11:00:40 PM
 */
package kbcgame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.html.*;
import java.awt.*;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javazoom.jl.player.Player;

/**
 *
 * @author DEEPAK
 */
public class KBCCallafriend extends javax.swing.JFrame
{  
    
    String correct_answer=null;
    
    final static int duration=50;   //means we dont want to change the value
    int i;
    Timer timer = new Timer( duration, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //throw new UnsupportedOperationException("Not supported yet.");
            if(i==100)
            {
                timer.stop();
                String str="<html>"+"<font color=\"green\">"+""+"</font>"+"</html>";
                try
                {
                    FileInputStream file=new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\calldisconnect.mp3");
                    Player p=new Player(file);
                    p.play();
                }
                catch(Exception e1)
                {
                    System.out.println(e);
                }
                
                JOptionPane.showMessageDialog(rootPane, "Time Over, Call Ended");
                
                try
                {
                    Connection con=DbConnectivity.connect();
                    PreparedStatement ps1 = con.prepareStatement("select * from KBC_QUESTION  where QUESTION='" + question + "'");
                    ResultSet rs1 = ps1.executeQuery();
                    while (rs1.next())
                    {
                        correct_answer = rs1.getString("CORRECT_ANSWER");
                    }
                }
                catch(Exception e1)
                {
                    System.out.println(e1);
                }
                
                JOptionPane.showMessageDialog(rootPane, "Correct Answer Is "+correct_answer);
                
                time1.start();
                setVisible(false);
            }
            
            i=i+1;
            jProgressBar1.setValue(i);
        }
    });
    
    Timer time1;
    String question=null;

    /** Creates new form KBCCallafriend */
    public KBCCallafriend(Timer time, String ques) {
        initComponents();
        time1=time;
        question=ques;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 550));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\beckam.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)), "Friend-1 :- Amir Khan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 180, 240);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\angelina.jpg")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)), "Friend-2 :- John", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 90, 170, 240);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\justin.jpg")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Friend-3 :- Hrithik", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 100, 190, 230);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Call Beckham");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 380, 110, 50);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Call Angelina");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 380, 100, 50);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Call Justin");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 380, 110, 50);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(5, 490, 790, 27);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\hepp.jpg")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)), "Call A Friend", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 520);

        setSize(new java.awt.Dimension(818, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
    JOptionPane.showMessageDialog(this, "You Will Get Only 10 Seconds To Call Beckam");
    try
    {
            FileInputStream file=new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\ringring.mp3");
            Player p=new Player(file);
            p.play();
    }
    catch(Exception e)
    {
        
    }
    String str1="<html>"+"<font color=\"red\">"+""+"</font>"+"</html>";
    timer.start();
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    
    JOptionPane.showMessageDialog(this, "You Will Get Only 10 Seconds To Call Angelina");
    try
    {
            FileInputStream file=new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\ringring.mp3");
            Player p=new Player(file);
            p.play();
    }
    catch(Exception e)
    {
        
    }
        String str1="<html>"+"<font color=\"red\">"+""+"</font>"+"</html>";
        timer.start();
    
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    
    JOptionPane.showMessageDialog(this, "You Will Get Only 10 Seconds To Call Justin");
    try
    {
            FileInputStream file=new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\ringring.mp3");
            Player p=new Player(file);
            p.play();
    }
    catch(Exception e)
    {
        
    }
    String str1="<html>"+"<font color=\"red\">"+""+"</font>"+"</html>";
    timer.start();
    
}//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KBCCallafriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KBCCallafriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KBCCallafriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KBCCallafriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KBCCallafriend(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
