/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayGame.java
 *
 * Created on Mar 10, 2013, 1:12:07 AM
 */
package kbcgame;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javazoom.jl.player.Player;

/**
 *
 * @author DEEPAK
 */
public class PlayGame extends javax.swing.JFrame {

    /**
     * Creates new form PlayGame
     */
    
    String name1=null;
    String email1;
    
    int status1=0;
    int status2=1;
    
    int win_amount = 0;
    
    ResultSet rs;
    
    boolean doubletip = false;

    PlayGame(String email) {
        initComponents();
        email1 = email;
        setResizable(false);
//        throw new UnsupportedOperationException("Not yet implemented");
    }

    
    final static int duration=1000;
    int i=30;
    
    Timer time=new Timer(duration, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            //throw new UnsupportedOperationException("Not supported yet.");
            
            if(i==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Your Time Is Over, You have lost the game");
                JOptionPane.showMessageDialog(rootPane, "Your Winning Amount Is : Rs. " + win_amount);
                JOptionPane.showMessageDialog(rootPane, "Thanks For Playing the Game");
                
                UserPanel up=new UserPanel(email1);
                up.setVisible(true);
                setVisible(false);
                
                time.stop();
            }
            i=i-1;
            jLabel6.setText(String.valueOf(i));
            
        }
    });
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(70, 421, 230, 30);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(420, 420, 230, 30);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(70, 490, 230, 30);

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(420, 491, 230, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUESTION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 305, 620, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Lock Answer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 450, 130, 40);

        jButton2.setText("QUIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(830, 510, 60, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ff.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 60, 80, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/callafriend.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(750, 130, 80, 50);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/audiencepoll.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(750, 200, 80, 50);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("WELCOME :-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 10, 90, 17);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 40, 110, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Score Is :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 50, 103, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 70, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rs");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 70, 17, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("..........");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 400, 64, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("30");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 450, 50, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\kbc.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 920, 550);

        setSize(new java.awt.Dimension(920, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:

    int a1;

    a1 = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want To Use Life Line - 50-50");
    if (a1 == 0)
    {
        time.stop();
        
        String ans = "";
        String ans1 = jRadioButton1.getText();
        String ans2 = jRadioButton2.getText();
        String ans3 = jRadioButton3.getText();
        String ans4 = jRadioButton4.getText();
    
        try
        {
            FileInputStream file = new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\lifeline.mp3");
            Player p = new Player(file);
            p.play();
            Connection con=DbConnectivity.connect();
            PreparedStatement ps1 = con.prepareStatement("select CORRECT_ANSWER from KBC_QUESTION where QUESTION='" + jLabel1.getText() + "'");
            ResultSet rs1 = ps1.executeQuery();
            while (rs1.next())
            {
                ans = rs1.getString("CORRECT_ANSWER");
            }

            if (ans.equals(ans1))
            {
                jRadioButton2.setEnabled(false);
                jRadioButton2.setForeground(Color.gray);
                jRadioButton3.setEnabled(false);
                jRadioButton3.setForeground(Color.gray);
            }
            else if (ans.equals(ans2))
            {
                jRadioButton3.setEnabled(false);
                jRadioButton3.setForeground(Color.gray);
                jRadioButton4.setEnabled(false);
                jRadioButton4.setForeground(Color.gray);
            }
            else if (ans.equals(ans3))
            {
                jRadioButton1.setEnabled(false);
                jRadioButton1.setForeground(Color.gray);
                jRadioButton2.setEnabled(false);
                jRadioButton2.setForeground(Color.gray);
            }
            else if (ans.equals(ans4))
            {
                jRadioButton1.setEnabled(false);
                jRadioButton1.setForeground(Color.gray);
                jRadioButton3.setEnabled(false);
                jRadioButton3.setForeground(Color.gray);
            }

            con.close();
            
            
            time.start();
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        jButton3.setEnabled(false);
    }

}//GEN-LAST:event_jButton3ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    
    time.start();
    
    try
    {
        Connection con=DbConnectivity.connect();
        PreparedStatement ps=con.prepareStatement("select * from KBC_REGISTRATION where EMAIL_ID='"+email1+"'");
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
                name1=rs.getString("NAME");
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }

    jLabel16.setText(name1);
    
    String question1=null;
    String option1=null;
    String option2=null;
    String option3=null;
    String option4=null;
    
    
    
    try
    {
        
        Connection con=DbConnectivity.connect();
        Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = s.executeQuery("SELECT * FROM KBC_QUESTION order by rand()");
        Statement s1 = con.createStatement();
        rs.first();
        question1 = rs.getString("QUESTION");
        option1=rs.getString("OPTION_A");
        option2=rs.getString("OPTION_B");
        option3=rs.getString("OPTION_C");
        option4=rs.getString("OPTION_D");
        
        
        jLabel1.setText(question1);
        jRadioButton1.setText(option1);
        jRadioButton2.setText(option2);
        jRadioButton3.setText(option3);
        jRadioButton4.setText(option4);
          }
    catch (Exception e)
    {
        System.out.println(e);
    }


}//GEN-LAST:event_formWindowOpened

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:

//    timer.stop();
 
    String question=jLabel1.getText();
    
    String correct_answer = null;

    String user_answer = "";
    if (jRadioButton1.isSelected()) {
        user_answer = jRadioButton1.getText();
    }
    if (jRadioButton2.isSelected()) {
        user_answer = jRadioButton2.getText();
    }
    if (jRadioButton3.isSelected()) {
        user_answer = jRadioButton3.getText();
    }
    if (jRadioButton4.isSelected()) {
        user_answer = jRadioButton4.getText();
    }
    
      
         try
         {
        Connection con=DbConnectivity.connect();
        PreparedStatement ps1 = con.prepareStatement("select * from KBC_QUESTION  where QUESTION='" + question + "'");
        ResultSet rs1 = ps1.executeQuery();
          
        while (rs1.next())
        {
            correct_answer = rs1.getString("CORRECT_ANSWER");
        }
        
        if (user_answer.equals(correct_answer))
        {
            time.stop();
            
            JOptionPane.showMessageDialog(this, "Your answer is correct");
            
            win_amount=win_amount+1000;
            jLabel3.setText(String.valueOf(win_amount));
                        
            try
            {
                FileInputStream file = new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\right.mp3");
                Player p = new Player(file);
                p.play();
            }
            catch (Exception e)
            {
                System.out.println(e);
            }
            
            JOptionPane.showMessageDialog(this, "You have won "+win_amount+" Rs");
            
         
            
            buttonGroup1.clearSelection();
            
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton1.setForeground(Color.white);
            jRadioButton2.setForeground(Color.white);
            jRadioButton3.setForeground(Color.white);
            jRadioButton4.setForeground(Color.white);
            
            i=31;
            time.start();
            
            String question1=null;
            String option1=null;
            String option2=null;
            String option3=null;
            String option4=null;
            
            rs.next();
            question1 = rs.getString("QUESTION");
            option1=rs.getString("OPTION_A");
            option2=rs.getString("OPTION_B");
            option3=rs.getString("OPTION_C");
            option4=rs.getString("OPTION_D");
            
            Connection con11=DbConnectivity.connect();
            PreparedStatement ps11=con11.prepareStatement("update KBC_QUESTION set STATUS='"+status2+"' where QUESTION='"+question1+"'");
            ps11.executeUpdate();

            jLabel1.setText(question1);
            jRadioButton1.setText(option1);
            jRadioButton2.setText(option2);
            jRadioButton3.setText(option3);
            jRadioButton4.setText(option4);
            
        }
        else
        {
            time.stop();
            
            if (doubletip == true)
            {
                time.start();
                
                JOptionPane.showMessageDialog(rootPane, "Your Answer Is Incorrect");
                JOptionPane.showMessageDialog(rootPane, "You Have One More Chance To Answer");
                
                if(jRadioButton1.isSelected()==true)
                {
                    jRadioButton1.setEnabled(false);
                    jRadioButton1.setForeground(Color.gray);
                }
                if(jRadioButton2.isSelected()==true)
                {
                    jRadioButton2.setEnabled(false);
                    jRadioButton2.setForeground(Color.gray);
                }
                if(jRadioButton3.isSelected()==true)
                {
                    jRadioButton3.setEnabled(false);
                    jRadioButton3.setForeground(Color.gray);
                }
                if(jRadioButton4.isSelected()==true)
                {
                    jRadioButton4.setEnabled(false);
                    jRadioButton4.setForeground(Color.gray);
                }
                
                buttonGroup1.clearSelection();
                
                doubletip = false;
                
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Your Answer Is Incorrect");
                JOptionPane.showMessageDialog(rootPane, "Your Winning Amount Is : Rs. " + win_amount);
                JOptionPane.showMessageDialog(rootPane, "Thanks For Playing the Game");

                Date d=new Date();
                SimpleDateFormat sdf1=new SimpleDateFormat("dd:MM:yyyy");
                SimpleDateFormat sdf2=new SimpleDateFormat("HH:mm:ss");
                
                PreparedStatement ps2 = con.prepareStatement("insert into KBC_SCORES values(?,?,?,?,?)");
                ps2.setString(1, email1);
                ps2.setString(2, name1);
                ps2.setInt(3, win_amount);
                ps2.setString(4, sdf1.format(d));
                ps2.setString(5, sdf2.format(d));
                ps2.executeQuery();
                
                Connection con11=DbConnectivity.connect();
                PreparedStatement ps11=con11.prepareStatement("update KBC_QUESTION set STATUS='"+status1+"'");
                ps11.executeUpdate();

                UserPanel up=new UserPanel(email1);
                up.setVisible(true);
                setVisible(false);
            }
        }

        con.close();
        
    }
    catch (Exception e)
    {
        System.out.println(e);
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:

    int ab = 0;
    ab = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want To Use Life-Line (Call A Friend)");
    if (ab == 0)
    {
        time.stop();
        
        jButton4.setEnabled(false);
        
        try
        {
            FileInputStream file = new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\lifeline.mp3");
            Player p = new Player(file);
            p.play();
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        
        String question=jLabel1.getText();
        
        KBCCallafriend kbccaf = new KBCCallafriend(time, question);
        kbccaf.setVisible(true);
    }

}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:

    int abc = 0;
    abc = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want To Use Life-Line (Audience Poll)");
    
    if (abc == 0)
    {
        time.stop();
        
        jButton5.setEnabled(false);
        
        try
        {
            FileInputStream file = new FileInputStream("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\Audio\\lifeline.mp3");
            Player p = new Player(file);
            p.play();
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        
        String question = jLabel1.getText();
        KBCAudiencepoll kbcap = new KBCAudiencepoll(question, time);
        kbcap.setVisible(true);
        
    }

}//GEN-LAST:event_jButton5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:

    int quit;
    quit = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want To Quit The Game");
    if (quit == 0)
    {
        
        time.stop();
        
        JOptionPane.showMessageDialog(rootPane, "Your Winning Amount Is : Rs. " + win_amount);
        JOptionPane.showMessageDialog(rootPane, "Thanks For Playing the Game");

        Date d=new Date();
        SimpleDateFormat sdf1=new SimpleDateFormat("dd:MM:yyyy");
        SimpleDateFormat sdf2=new SimpleDateFormat("HH:mm:ss");
        
        try
        {
            Connection con=DbConnectivity.connect();
            PreparedStatement ps2 = con.prepareStatement("insert into KBC_SCORES values(?,?,?,?,?)");
            ps2.setString(1, email1);
            ps2.setString(2, name1);
            ps2.setInt(3, win_amount);
            ps2.setString(4, sdf1.format(d));
            ps2.setString(5, sdf2.format(d));
            ps2.executeUpdate();

            UserPanel up=new UserPanel(email1);
            up.setVisible(true);
            setVisible(false);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }

}//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:

        jButton1.setBackground(Color.green);

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO aedd your handling code here:

        jButton1.setBackground(Color.lightGray);

    }//GEN-LAST:event_jButton1MouseExited

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayGame(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
