/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserRegistration.java
 *
 * Created on Mar 10, 2013, 5:09:20 PM
 */
package kbcgame;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author DEEPAK
 */
public class UserRegistration extends javax.swing.JFrame {

    /** Creates new form UserRegistration */
    public UserRegistration() {
        initComponents();
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 595));
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 204));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 70, 240, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton1.setText("MALE");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(130, 270, 65, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton2.setText("FEMALE");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(270, 270, 83, 25);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delhi", "Noida", "Faridabad", "Gurgaon", "Chandigarh", "Nalagarh", "Hisar" }));
        jComboBox1.setBorder(null);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 330, 270, 50);

        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 204));
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 130, 240, 40);

        jPasswordField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 204));
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(120, 190, 240, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 450, 170, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 500, 50, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 40, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Email Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 56, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 200, 67, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 280, 50, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("City");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 350, 27, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("USER REGISTRATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(135, 31, 194, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home\\Documents\\NetBeansProjects\\KBC mysql\\src\\images\\hepp.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 460, 570);

        setSize(new java.awt.Dimension(449, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
    String uname=jTextField1.getText();
    String email=jTextField2.getText();
    String password=jPasswordField1.getText();
    
    String gender="";
    if(jRadioButton1.isSelected())
    {
        gender="Male";
    }
    if(jRadioButton2.isSelected())
    {
        gender="Female";
    }
    
    String city=(String) jComboBox1.getSelectedItem();
    
    if(uname.equals("") || uname==null)
    {
        JOptionPane.showMessageDialog(this, "Name cannot be null");
    }
    else if(uname.length()<3 || uname.length()>25)
    {
        JOptionPane.showMessageDialog(this, "Name should be of length 3-25 characters");
    }
    else if(email.equals("") || email==null)
    {
        JOptionPane.showMessageDialog(this, "Email cannot be null");
    }
    else if(password.equals("") || password==null)
    {
        JOptionPane.showMessageDialog(this, "Password cannot be null");
    }
    else if(gender.equals("") || gender==null)
    {
        JOptionPane.showMessageDialog(this, "Gender cannot be null");
    }
    else if(city.equals("") || city==null)
    {
        JOptionPane.showMessageDialog(this, "City cannot be null");
    }
    else
    {
        try
        {
            Connection con=DbConnectivity.connect();
            PreparedStatement ps=con.prepareStatement("insert into KBC_REGISTRATION values (?,?,?,?,?)");
            ps.setString(1, email);
            ps.setString(2, uname);
            ps.setString(3, password);
            ps.setString(4, gender);
            ps.setString(5, city);
            
            ps.executeUpdate();
            con.close();

            JOptionPane.showMessageDialog(rootPane, "Your Account Has Successfully Created");
            UserPanel up=new UserPanel(email);
            up.setVisible(true);
            setVisible(false);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    
    MainPage mp=new MainPage();
    mp.setVisible(true);
    setVisible(false);
    
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
